schema_version: 1

context:
  name: geofabrik-mock-server
  version: 0.1.1
  python_min: "3.10"
  date: "2026-05-14"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/travishathaway/geofabrik-mock-server/archive/refs/tags/${{ version }}.tar.gz
  sha256: 86595a653ce723969bb84ae1ef72c60e639067e55b7faa102adac7527144dd53

build:
  number: 0
  noarch: python
  script:
    file: build.sh
    env:
      GEOFABRIK_MOCK_SERVER_DATE: ${{ date }}
  python:
    entry_points:
      - gms = geofabrik_mock_server.cli:main

requirements:
  host:
    - python >=${{ python_min }}
    - hatchling >=1.27.0
    - pip
    # These are needed here because the build.sh runs the CLI itself
    # runs during the build.
    - click
    - flask
    - requests
  run:
    - python >=${{ python_min }}
    - click
    - flask
    - requests

tests:
  - python:
      pip_check: true
  - requirements:
      run:
        - python >=${{ python_min }}
    script:
      - gms --help

about:
  summary: HTTP server that serves a mock version of download.geofabrik.de
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/travishathaway/geofabrik-mock-server

extra:
  recipe-maintainers:
    - travishathaway
