# This project hasn't actually been released yet:
# - https://github.com/osm2pgsql-dev/themepark/issues/20
#
# Once it's been released, I'll come back and package it
#
context:
  version: "0.1.0"

package:
  name: osm2pgsql-themepark
  version: ${{ version }}

source:
 - url: https://github.com/travishathaway/osm2pgsql-themepark/archive/refs/heads/luarocks.tar.gz
   sha256: 16ce2ad25692f8231b0ab5f52a44622e2160af44f95f6f6a4953599ed993915a

build:
  number: 1
  noarch: generic
  script:
    - luarocks make --tree="${PREFIX}" --deps-mode=none --no-manifest osm2pgsql-themepark-scm-1.rockspec

requirements:
  host:
    - lua
    - luarocks
  run:
    - lua
    - osm2pgsql

# TODO: It would be nice to have a test script that starts a PostgreSQL instance and then imports
# some data using osm2pgsql.
# tests:
#   - script:
#     - osm2pgsql

about:
  homepage: https://osm2pgsql.org/themepark
  license: Apache-2.0
  license_file:
    - LICENSE
  summary: A framework for creating osm2pgsql flex configurations
  description: This is a framework for creating osm2pgsql configurations assembled from many building blocks. Some of those blocks are provided in this repository, others you can add yourself.
  documentation: https://osm2pgsql.org/themepark
  repository: https://github.com/osm2pgsql-dev/osm2pgsql-themepark

extra:
  recipe-maintainers:
    - travishathaway
